from pathlib import Path

DOG = 0
CAT = 1
TRAINING_START_IDX = 1
TRAINING_END_IDX = 5001
VALIDATING_START_IDX = 5002
VALIDATING_END_IDX = 10003 # 10,003

IMAGES_PATH = Path('../images')
PROCESSING_PATH = Path('../proc')
DOGS_PATH = IMAGES_PATH / 'dog'
CATS_PATH = IMAGES_PATH / 'cat'
CLASSIFIER_PATH = "../classifier.h5"